#!/bin/sh

# En son üzerinde çalışılan girdiyi düzenle.
#
# Argüman opsiyoneldir ve kategori belirtir.
#
# Argüman verilmezse kategori olarak dizin değişme tarihi en yeni olan
# kategori seçilir.

set -e

. _scripts/util.sh

currentpost=$(currentpost "$@")
if [ -z "$currentpost" ]; then
	internalerror "güncel posta hesaplanamadı"
fi
if [ ! -f "$currentpost" ]; then
	internalerror "güncel posta varolmayan bir posta olarak hesaplandı"
fi

editor "$currentpost"

# Dosyanın stage'te olduğundan emin ol.  Bunu yapmazsak iki olumsuz seçenek var:
# - commit için gönderi ismi gerekecek ör. "git commit <gönderi>"
# - "git commit -a" ile gönderilecek (bk. hepsi bir arada komitleme sendromu)
# Artık "stage"e alındığından sadece "git commit" yeterli.
git add "$currentpost"
